import "~/styles/globals.css";

import { type Metadata } from "next";
import { Onest } from "next/font/google";

import { ProfileBadge } from "~/components/component/ProfileBadge";
import { Sidebar } from "~/components/component/Sidebar";
import { ScrollArea } from "~/components/ui/scroll-area";
import { getServerAuthSession } from "~/server/auth";
import { TRPCReactProvider } from "~/trpc/react";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { imageFileRouter } from "./api/uploadthing/core";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = Onest({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();

  return (
    <html lang="en" className={font.className}>
      <body>
        <NextSSRPlugin routerConfig={extractRouterConfig(imageFileRouter)} />
        <TRPCReactProvider>
          <main className="grid h-screen grid-cols-[300px_auto_300px] lg:mx-[0] xl:mx-[120px]">
            <div className="h-full border-r-2 border-r-border p-6">
              <Sidebar />
            </div>
            <ScrollArea>
              <div className="h-screen">{children}</div>
            </ScrollArea>
            <div className="border-l-2 border-l-border p-6">
              {session?.user.name ? (
                <ProfileBadge
                  name={session.user.name}
                  username={session.user.name
                    .toLocaleLowerCase()
                    .replaceAll(" ", "_")}
                  profilePicture={session.user.image!}
                />
              ) : null}
            </div>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
